### ISSUE TITLE
I have code you may use if you like

### ISSUE THREAD

**Issue by ghost** [SpikeHD/gm-sysinfo#2]
I don't have the time to create a pull request, but Rust can be combined with C++ I read online as long as C++ exceptions are not being used, and my project does not use those. In case you wanted to borrow any of my code to add new features to your extension, I thought I'd give you the option to do so, and give you the link, if it interests you:

https://github.com/time-killer-games/libsysinfo

My extension has some features yours does not, and vise-versa. No need to credit me or use the same license.

**Comment by SpikeHD** [comment]
I appreciate the heads-up!
